import Image from "next/image";
import React from "react";

const Tape = () => {
  return (
    <div className='tape'>
      <span>Figma's</span>
      <Image
        src='/assets/icons/marquee1.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>marvelously</span>
      <Image
        src='/assets/icons/marquee2.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>considered</span>
      <Image
        src='/assets/icons/marquee3.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>collection</span>
      <Image
        src='/assets/icons/marquee4.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>of</span>
      <Image
        src='/assets/icons/marquee5.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>objects</span>
      <Image
        src='/assets/icons/marquee6.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>for</span>
      <Image
        src='/assets/icons/marquee7.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>our</span>
      <Image
        src='/assets/icons/marquee8.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>time</span>
      <Image
        src='/assets/icons/marquee9.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
      <span>on</span>
      <Image
        src='/assets/icons/marquee1.svg'
        alt=''
        role='presentation'
        width={80}
        height={80}
      />
    </div>
  );
};

export default Tape;
