export const slides = [
  {
    src: "swiper1.jpg",
    width: "400",
    height: "300",
    description: "Design in bloom tee",
  },
  {
    src: "swiper2.jpg",
    width: 400,
    height: 300,
    description: "Version history coach jacket",
    style: {
      flex: "0 0 124%",
      width: "105%",
      position: "relative",
      left: "50%",
      transform: "translateX(-50%)",
    },
  },
  {
    src: "swiper3.jpg",
    width: 400,
    height: 300,
    description: "Gridlock washi tape",
  },
  {
    src: "swiper4.jpg",
    width: 400,
    height: 300,
    description: "Tidy up tee",
  },
  {
    src: "swiper5.jpg",
    width: 400,
    height: 300,
    description: "Design in bloom tee",
    style: {
      flex: "0 0 124%",
      width: "110%",
      position: "relative",
      left: "50%",
      transform: "translateX(-50%)",
    },
  },
  {
    src: "swiper6.jpg",
    width: 400,
    height: 300,
    description: "Dress code hat",
  },
  {
    src: "swiper7.jpg",
    width: 400,
    height: 300,
    description: "Shape up tee",
  },
  {
    src: "swiper8.jpg",
    width: 400,
    height: 300,
    description: "Toolkit pin",
  },
  {
    src: "swiper9.jpg",
    width: 400,
    height: 300,
    description: "Band together socks",
  },
  {
    src: "swiper10.jpg",
    width: 400,
    height: 300,
    description: "Framework tee",
  },
];
