"use client";
import type { Metadata } from "next";
import "../styles/globals.css";
import StyledComponentsRegistry from "./registry";
import { QueryClient, QueryClientProvider, Hydrate } from "react-query";
import React, { useEffect } from "react";
// import { ReactQueryDevtools } from "react-query/devtools";
// import { Hydrate as SWRHydrate } from "swr";

// export const metadata: Metadata = {
//   title: "The Figma Store | by Alejo Avenali",
//   description: "Generated by create next app",
//   icons: {
//     icon: [
//       {
//         url: "/assets/favicon.svg",
//         href: "/assets/favicon.svg",
//       },
//     ],
//   },
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClientRef: any = React.useRef();

  if (!queryClientRef.current) {
    queryClientRef.current = new QueryClient();
  }

  useEffect(() => {
    let link: any = document.querySelector("link[rel~='icon']");
    if (!link) {
      link = document.createElement("link");
      link.rel = "icon";
      document.getElementsByTagName("head")[0].appendChild(link);
    }
    link.href = "/assets/favicon.svg";
  }, []);

  return (
    <html lang='en'>
      <QueryClientProvider client={queryClientRef.current}>
        <StyledComponentsRegistry>
          <body>{children}</body>
        </StyledComponentsRegistry>
      </QueryClientProvider>
    </html>
  );
}
